# Generated by Django 3.1.4 on 2020-12-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Artist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(help_text='Billing Address', max_length=255)),
                ('Phone', models.CharField(max_length=13)),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('Exhibition_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
                ('Exhibition_Name', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=255)),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('Painting_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Painting', models.ImageField(null=True, upload_to='paintings/')),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Year', models.DateField()),
                ('Sold', models.BooleanField(default=False)),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('Artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_artist', to='ArtGalleryApp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('Artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_painting_artist', to='ArtGalleryApp.artist')),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_to_customer', to='ArtGalleryApp.customer')),
                ('Painting_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_bought', to='ArtGalleryApp.painting')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Address', models.CharField(max_length=255)),
                ('Office', models.CharField(max_length=255)),
                ('Slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('Artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_addresses', to='ArtGalleryApp.artist')),
            ],
        ),
    ]
