# Generated by Django 3.1.4 on 2020-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
