# Generated by Django 3.1.4 on 2020-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0002_auto_20201206_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist_Address',
            new_name='ArtistAddress',
        ),
        migrations.AlterField(
            model_name='artist',
            name='Artist_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
