# Generated by Django 3.1.4 on 2020-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0004_buy_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Painting_Name',
            field=models.CharField(default='NOT PROVIDED', max_length=40),
        ),
    ]
