# Generated by Django 3.1.4 on 2020-12-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0005_buy_painting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='Year',
            field=models.CharField(max_length=4),
        ),
    ]
