# Generated by Django 3.1.4 on 2020-12-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0006_auto_20201207_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='painting',
            name='Painting_Name',
            field=models.CharField(default='Not Provided', max_length=59),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Painting_Name',
            field=models.CharField(blank=True, max_length=59),
        ),
    ]
