# Generated by Django 3.1.4 on 2020-12-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0011_auto_20201207_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaddress',
            name='Artist_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_addresses', to='ArtGalleryApp.artist', unique=True),
        ),
    ]
