# Generated by Django 3.1.4 on 2020-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGalleryApp', '0013_auto_20201209_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='First_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Last_Name',
            field=models.CharField(max_length=20),
        ),
    ]
